"""Generate RESULTS.md, the reference texts and labels.json for the real corpus.

    python corpus/real/report.py

Reads the transcripts next to this script, fetches the Gutenberg text
(cached, not committed), cuts one reference per story, scores accuracy
and production, runs the default detectors against the reviewed
expectations, and writes RESULTS.md. Never edit RESULTS.md by hand.
"""

from __future__ import annotations

import json
import re
import sys
import unicodedata
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent / "src"))

from trusted_transcription.detectors import ALL_DETECTORS  # noqa: E402
from trusted_transcription.eval.detector_bench import (  # noqa: E402
    load_labels,
    render,
    run_detector_bench,
)
from trusted_transcription.eval.engine_bench import accuracy, production  # noqa: E402
from trusted_transcription.models import TranscriptResult  # noqa: E402

GUTENBERG = "https://www.gutenberg.org/cache/epub/11714/pg11714.txt"
BOOK = HERE / "audio" / "pg11714.txt"

# Story heading in the Gutenberg text, and the heading that follows it.
STORIES = {
    "01_la_becasse": ("LA BÉCASSE", "CE COCHON DE MORIN"),
    "03_la_folle": ("LA FOLLE", "PIERROT"),
    "05_menuet": ("MENUET", "LA PEUR"),
    "10_en_mer": ("EN MER", "UN NORMAND"),
}

# Reviewed by hand on the engine output. The reader's closing words are
# followed by seconds of silence, on which the engine returns a subtitle
# credit that nobody read: a real phantom phrase, expected as such.
EXPECTED: dict[str, list[str]] = {
    "01_la_becasse": ["silence_hallucination", "trailing_credit"],
}


def fold(s: str) -> str:
    stripped = "".join(c for c in unicodedata.normalize("NFKD", s) if not unicodedata.combining(c))
    return stripped.upper()


def heading(title: str) -> re.Pattern[str]:
    return re.compile(r"^\s*" + re.escape(fold(title)) + r"\s*$", re.M)


def story(text: str, title: str, next_title: str) -> str:
    folded = fold(text)
    heads = [m.start() for m in heading(title).finditer(folded)]
    if not heads:
        raise SystemExit(f"heading not found: {title}")
    # The first occurrence is the heading; a table of contents sits at the end of the file.
    start = heads[0]
    tail = folded[start + 1 :]
    end_m = heading(next_title).search(tail)
    end = start + 1 + end_m.start() if end_m else len(text)
    body = re.sub(r"^\s*" + re.escape(title) + r"\s*$", "", text[start:end], count=1, flags=re.M)
    return re.sub(r"\s+", " ", body).strip()


def main() -> None:
    if not BOOK.exists():
        BOOK.parent.mkdir(parents=True, exist_ok=True)
        urllib.request.urlretrieve(GUTENBERG, BOOK)
    book = BOOK.read_text(encoding="utf-8", errors="replace")

    rows = []
    labels: dict[str, list[str]] = {}
    for key, (title, nxt) in STORIES.items():
        src = HERE / f"{key}.json"
        if not src.exists():
            continue
        ref = story(book, title, nxt)
        (HERE / f"{key}.reference.txt").write_text(ref + "\n", encoding="utf-8")
        doc = json.loads(src.read_text(encoding="utf-8"))
        hyp = " ".join(s["text"] for s in doc["segments"])
        rows.append((title, doc["metadata"]["audio_duration_sec"], len(doc["segments"]),
                     accuracy(ref, hyp), production(ref, hyp)))
        labels[f"{key}.json"] = EXPECTED.get(key, [])
    (HERE / "labels.json").write_text(json.dumps(labels, indent=2) + "\n", encoding="utf-8")

    report = run_detector_bench(HERE, load_labels(HERE / "labels.json"), list(ALL_DETECTORS))
    fired = {}
    for key in labels:
        t = TranscriptResult.model_validate_json((HERE / key).read_text(encoding="utf-8"))
        fired[key] = [
            (f.detector, f.segment_index, f.reason[:90]) for d in ALL_DETECTORS for f in d.detect(t)
        ]

    lines = [
        "# Results on the public corpus", "",
        "Generated by `corpus/real/report.py`; do not edit by hand.", "",
        "Engine: faster-whisper `small`, int8, CPU, French, beam 5.",
        "Reference: Project Gutenberg #11714.", "",
        "## Engine bench — accuracy and production against the book text", "",
        "| Chapter | Audio | Segments | Accuracy | Production |", "|---|---:|---:|---:|---:|",
    ]
    for title, dur, n, acc, prod in rows:
        lines.append(f"| {title.title()} | {dur / 60:.1f} min | {n} | {acc:.1%} | {prod:.1%} |")
    lines += [
        "",
        "Accuracy is the share of produced words that align with the book; production the words",
        "returned relative to the book. Production above 100% is the LibriVox announcement at each",
        "end of the recording, which is not in the book; the gap in accuracy is the reader's",
        "liberties, the engine's errors and the alignment's strictness.", "",
        "## Detector bench — against the reviewed expectations", "",
        "```", render(report), "```", "",
    ]
    for key, flags in fired.items():
        if flags:
            lines.append(f"### {key}")
            lines += [f"- `{d}` on segment {i}: {r}" for d, i, r in flags]
            lines.append("")
    (HERE / "RESULTS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    sys.exit(0 if report.clean else 1)


if __name__ == "__main__":
    main()
